apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
        - image: docker.io/otrofox/flask-docker:1.0
          name: flask-docker
          ports:
            - containerPort: 5000
